version: '3.7'
services:
  redis:
    image: redis:4.0
    container_name: chat_redis
    ports:
        - "6378:6379"
    networks:
        - network

  db:
      image: postgres
      restart: unless-stopped
      container_name: chat_db
      environment:
          - POSTGRES_DB=${DB_DATABASE}
          - POSTGRES_USER=${DB_USERNAME}
          - POSTGRES_PASSWORD=${DB_PASSWORD}
      ports:
          - "5555:5432"
      volumes:
          - ./postgres-data:/var/lib/postgresql/data
      networks:
          - network

networks:
  network:
    driver: bridge
    name: chat_network
